name: praktikum_filter_camera
description: Project gabungan praktikum kamera + carousel filter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Kamera / ambil foto
  image_picker: ^1.1.2

  # Untuk file
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sample.jpg
